@startuml
title Diagrama de Secuencia - HU2: Crear publicaciones de insumos médicos

actor "Usuario" as User
participant "Cliente (Frontend)" as Client
participant "PublicationsController" as Controller
participant "PublicationsService" as Service
database "Publication \n (PostgreSQL)" as DB

User -> Client: Llena formulario de publicación
Client -> Controller: create(body: JSON)
Controller -> Service: create(CreatePublicationDto)

Service -> Service: Validar (expirationDate > fecha actual)

alt [Fecha inválida (pasada)]
    Service --> Controller: Error (Exception)
    Controller --> Client: Error (400 Bad Request)
    Client --> User: Muestra error de validación
else [Fecha válida]
    Service -> DB: create({ ..., expirationDate, isActive: true, user: dto.userId })
    Service -> DB: save(publication)
    DB --> Service: publication guardada
    
    Service --> Controller: publication
    Controller --> Client: Response (Éxito)
    Client --> User: Muestra mensaje "Publicación creada con éxito"
end

@enduml
