@startuml
' Formato para los modelos de domineo
hide empty members
hide circle
skinparam classBackgroundColor White
skinparam classBorderColor Black

' Definición de Conceptos
class Usuario
class Administrador
class Publicacion
class Categoria
class Transaccion
class detailTransaccion
class Calificacion
class Reporte

' Relaciones y Multiplicidades
Usuario "1" -- "0..*" Publicacion : crea >
Publicacion "0..*" -- "1" Categoria : pertenece a >

Usuario "1" -- "0..*" Transaccion : realiza >

'relacion 1 a 1 para evitar registros duplicados.
detailTransaccion "1" -- "1" Publicacion : asociada a >

Transaccion "1" -- "0..2" Calificacion : recibe >
Usuario "1" -- "0..*" Calificacion : posee >

detailTransaccion "0..*" -- "1" Usuario : intercambia >
detailTransaccion "1" -- "1" Transaccion : contiene >

Usuario "1" -- "0..*" Reporte : emite >
Reporte "0..*" -- "1" Publicacion : señala >

Administrador  --  Reporte : revisa >
Administrador  --  Usuario : gestiona >
@enduml